apiVersion: v1
kind: Pod
metadata:
  name: centos-vulnerability-public
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/public_project/centos7:v1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-vulnerability-public
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-clean-public
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/public_project/centos7:v2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-clean-public
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-vulnerability-private
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/private_project/centos7:v1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-vulnerability-private
  restartPolicy: Always
  imagePullSecrets:
  - name: private-creds
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-clean-private
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/private_project/centos7:v2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-clean-private
  restartPolicy: Always
  imagePullSecrets:
  - name: private-creds
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-clean-unsigned
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/signed_project/centos7:v1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-clean-unsigned
  restartPolicy: Always
  imagePullSecrets:
  - name: private-creds
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-clean-signed
spec:
  containers:
  - image: harbor.nevadacity.cf-app.com/signed_project/centos7:v2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: centos-clean-signed
  restartPolicy: Always
  imagePullSecrets:
  - name: private-creds
